import asyncio
import sys
from logging.config import fileConfig
from pathlib import Path

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.core.config import get_settings  # noqa: E402
from app.db.base import Base  # noqa: E402
from app.db.models import agent_run  # noqa: E402,F401
from app.db.models import destination_document  # noqa: E402,F401
from app.db.models import feedback  # noqa: E402,F401
from app.db.models import recommendation  # noqa: E402,F401
from app.db.models import tag_definition  # noqa: E402,F401
from app.db.models import tool_log  # noqa: E402,F401
from app.db.models import user  # noqa: E402,F401
from app.db.models.destination import DestinationCorpusBase  # noqa: E402

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Source the DB URL from the app's own Settings rather than duplicating it
# in alembic.ini, per the project's "settings only through config.py" rule.
config.set_main_option("sqlalchemy.url", get_settings().database.url)

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Two declarative bases feed autogenerate: app.db.base.Base (users,
# agent_runs, tool_logs, destination_documents, recommendations, feedback,
# tag_definitions) and DestinationCorpusBase (destinations - deliberately
# kept off Base, see app/db/models/destination.py). Alembic accepts a list
# of MetaData objects for target_metadata since 1.9.
target_metadata = [Base.metadata, DestinationCorpusBase.metadata]

# pgvector-specific DDL (HNSW indexes, the Vector column type's ops classes)
# is not reflected by Alembic's autogenerate, and migrations in this project
# have so far been hand-written rather than autogenerated. target_metadata
# is wired up regardless so `alembic check` / future autogenerate runs have
# something correct to diff against.

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """In this scenario we need to create an Engine
    and associate a connection with the context.

    """

    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""

    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
